baseURL = "https://business.anphabe.com/"
languageCode = "vi"
title = "My New Hugo Site"

theme = "business"

defaultContentLanguage = "vi"
paginate = 12
disableKinds = ['taxonomy', 'term']

[languages]
  [languages.vi]
    title = "Anphabe Business"
    weight = 1
  [languages.en]
    title = "Anphabe Business"
    weight = 2
    
[module]
  [[module.mounts]]
    source = "theme/"
    target = "static"
    lang   = "en"

[frontmatter]
  date = ["date", "publishDate", "lastmod", ":git"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]


[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "title"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5



